baseurl = "/"
languageCode = "zh-cn"
title = "A minimal Hugo blog"
theme = "xmin"
ignoreFiles = [
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$",
  "\\.knit\\.md$",
  "\\.utf8\\.md$"
]
footnotereturnlinkcontents = "↩"
disqusShortname = "xiaoxi404"

hasCJKLanguage = true
enableEmoji = true

[permalinks]
posts = "/post/:year/:month/:day/:slug/"
leet-code = "/leet-code/:year/:month/:day/:slug/"
csapp = "/study/csapp/:year/:month/:day/:slug/"
missing-semester = "/study/missing-semester/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "乱七八糟"
url = "posts/"
weight = 2

[[menu.main]]
name = "力扣"
url = "leet-code/"
weight = 3

[[menu.main]]
name = "学习"
url = "study/"
weight = 4

[[menu.main]]
name = "Subscribe"
weight = 5
url = "index.xml"

[params]
description = "A website built through Hugo and blogdown."
footer = "&copy; xiaoxi404 2022 -- {Year} | [Github](https://github.com/xiaoxi404) | Powered by [hugo](https://gohugo.io/) & [xmin](https://github.com/yihui/hugo-xmin)"

[markup.highlight]
codeFences = true

[markup.goldmark.renderer]
unsafe = true