baseurl = "/"
languageCode = "zh-cn"
title = "A minimal Hugo blog"
theme = "xmin"
ignoreFiles = [
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$",
  "\\.knit\\.md$",
  "\\.utf8\\.md$"
]
footnotereturnlinkcontents = "↩"

hasCJKLanguage = true
enableEmoji = true

[permalinks]
posts = "/post/:year/:month/:day/:slug/"
leet-code = "/leet-code/:year/:month/:day/:slug/"
csapp = "/csapp/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "posts"
url = "posts/"
weight = 2

[[menu.main]]
name = "leet-code"
url = "leet-code/"
weight = 3

[[menu.main]]
name = "csapp"
url = "csapp/"
weight = 4

[[menu.main]]
name = "Subscribe"
weight = 5
url = "index.xml"

[params]
description = "A website built through Hugo and blogdown."
footer = "&copy; [xiaoxi404](https://blog.nobody404.xyz) 2022 -- {Year} | [Github](https://github.com/xiaoxi404)"

[markup.highlight]
codeFences = true

[markup.goldmark.renderer]
unsafe = true